# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.example.com"

# Site title
title = "Your site"

# Language
languageCode = "en-EN"

# "yaml", "toml", "json"
metaDataFormat = "yaml"

# theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# pagination
paginate = 5
paginatePath = "page"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Your Name"
    email = "yourname@example.com"
    gravatarHash = "" # MD5 hash of your Gravatar email address
    sidebarDisplay = false
    copyrightDisplay = true

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Short description about your site"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-00"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Enable Disqus integration
    disqusShortname = "your_disqus_shortname"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "enten/hugo-boilerplate" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    rss = true  # switch to true to enable RSS icon link

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
