[tasks.serve]
description = "Build and serve the site locally"
run = "hugo serve --navigateToChanged"
[tasks.servedebug]
description = "Build and serve the site locally"
run = "hugo serve -D --navigateToChanged"
